### PR TITLE
Update install section

### PR DESCRIPTION
**Pull request by royopa**

### CODE REVIEW

**Comment by andrejsstepanovs** [comment]
This is pretty low from you @royopa. You just copy pasted my code! Would be much nicer if you could fork it like everybody else who is relying on my code. And after you did that you are requesting PR to inject your repo name? :-1:  
I'm asking you to add my library name in your readme.md ! "andrejsstepanovs/business-days-calculator".

**Comment by royopa** [comment]
Sorry @andrejsstepanovs but I did not understand your comment.
The project "https://github.com/nuxia/BusinessDayManipulator" is not mine! 
I only help the two projects "nuxia/BusinessDayManipulator" and "andrejsstepanovs/business-days-calculator" with my PR to install via command line in composer. I corrected you PR, thanks for the review.
Regards

**Comment by andrejsstepanovs** [comment]
:+1:

**Comment by andrejsstepanovs** [comment]
Thanks for this!

**Pull request merged**
